#!/bin/bash
git init -qqq
git remote add origin https://github.com/immakdas/docker-magento
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.vscode ./
rm -rf compose .git
git init
